spring:
  # 激活配置
  profiles:
    active: dev

jwt:
  tokenHeader: Authorization #JWT存储的请求头（http header，千万别动这个）
  secret: lgkz1LhZTwJ13V8VISfM #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头




minio:
  endpoint: http://8.140.135.67:9000
  bucketName: fcprofessional #存储桶名称
  accessKey: minio123 #访问的key
  secretKey: minio123 #访问的秘钥
