#开发环境的配置
server:
  port: 80
spring:
  #  database config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://8.140.135.67:3306/fc_profession_edu?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
      username: poly
      password: dg3FHFYl6NPnz84U3YAN
#      url: jdbc:mysql://127.0.0.1:3306/fc_profess_edu?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
#      username: root
#      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
      location: ./uploads
  redis:
    host: 8.140.135.67
    database: 0
    port: 6379
    password: iti1qVc9MSgf2jG4JasLnV7U7Uow9ucL6Bi0pU0gJ3ezi1wHR9ozyyz2NrUxuXdwUuCEKar6YmLVgUK4zqbRyNBKifKJgaFOGp7YXJlxcX2H1PGxRE4ynNB6nNvropAJVbPcFQ4oMqBXZ11nWhOBjMJzQ3bKrOTKoLrLc9DPomLDIujHAvtzoj7VERvXTr0TMgnn6Jy5rM9GsU9laravzX5V017yMNCvicbenY4N3RJZDdp98QviW6CpvbN2dINvlUqa3eh3yB6o1zSAgyehlKFvMPDPEDNY8PbWH0jTSwnvPbesuD42nt1DDZfLiJyh40yKPB6INAm1KIwKzEw95B8Dx6QUQCgu3siMFI0z7iAHCfzyA6fFo8C1UTAbGBiKqM2gg9vpsKG4CDGyQeESjT0Gqdor7OyYO9DC8s9PzpMWvSe1vgl4k5K32xdHeih5sjS6FzjIYd5s44Zguu9iySedidXbKIaXbGQO56dI8USPakBfMNsW
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.servlet.multipart.location}
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
