#开发环境的配置
server:
  port: 80
spring:
  #  database config
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #      url: jdbc:mysql://8.140.135.67:3306/fc_profession_edu?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
      #      username: poly
      #      password: dg3FHFYl6NPnz84U3YAN
      url: jdbc:postgresql://127.0.0.1:5432/tttt?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver
      initial-size: 5
      min-idle: 5
      max-active: 30
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
      location: ./uploads

  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.servlet.multipart.location}
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
